### ISSUE TITLE
Support RPC 0.4.0

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/starknet-jvm#280] opened 2023-07-25 13:56 UTC
### Feature Request

https://github.com/starkware-libs/starknet-specs/tree/v0.4.0-rc2

**Comment by THenry14** [comment] 2023-07-27 10:09
duplicate of https://github.com/software-mansion/starknet-jvm/issues/262

**Closed by THenry14** 2023-07-27 10:09 UTC
Labels: enhancement, blocked
